const Books = [
    {
        id : 0 ,
        book :  "The Lightning Thief" ,
        title : "Percy Jackson And The Olympians #1" ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        next : "/browse2" ,
        prev :"#" ,
        } ,
    {
        id : 1 ,
        book :  "Sea Of Monsters" ,
        title : "Percy Jackson And The Olympians #2"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        next : "/browse3" ,
        prev :"/browse1" ,
        } ,
    {
        id : 2 ,
        book :  "The Titan's Curse" ,
        title : "Percy Jackson And The Olympians #3"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        prev :"/browse2" ,
        next :"/browse4" ,
        } ,
    {
        id : 3 ,
        book :  "The Battle of Labyrinth" ,
        title : "Percy Jackson And The Olympians #4"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        prev :"/browse3" ,
        } ,
    {
        id : 4 ,
        book :  "The Last Olympian" ,
        title : "Percy Jackson And The Olympians #5"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
    
    {
        id :  5,
        book :  "The Lost Hero"  ,
        title :   "Heroes Of Olympus #1" ,
        author : "Rick Riordan" ,
        body : "500 Pages",
    } ,
    {
        id :  6,
        book :  "Son Of Neptune",
        title : "Heroes Of Olympus #2"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
    {
        id : 7 ,
        book :  "Mark OF Athena",
        title : "Heroes Of Olympus #3"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
    {
        id : 8 ,
        book :  "House OF Hades" ,
        title : "Heroes Of Olympus #4"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
    {
        id : 9 ,
        book :  "Blood Of Olympus" ,
        title : "Heroes Of Olympus #5"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
    {
        id : 10 ,
        book :  "The Hidden Oracle" ,
        title : "Trials Of Apollo#1"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
    {
        id : 11 ,
        book :  "The Dark Prophecy" ,
        title : "Trials Of Apollo#2"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
    {
        id : 12 ,
        book :  "The Burning Maze" ,
        title : "Trials Of Apollo#3"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",

        } ,
    {
        id : 13 ,
        book :  "The Tyrant Tomb" ,
        title : "Trials Of Apollo#4"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
    {
        id : 14 ,
        book :  "The Tower of Nero" ,
        title : "Trials Of Apollo#5"  ,
        author : "Rick Riordan" ,
        body : "500 Pages",
        } ,
        
                                                
]

export default Books;